### ISSUE TITLE
Pause/unpause Airflow DAGs through API

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#1]
**Description**
As a user of Airflow on Astronomer, I would like to be able to programmatically pause/unpause dags so I can more easily affect dag behavior (and possibly tie in with my own internal tooling) without having to log directly into Airflow.

**Example behavior:**
`astro pause {dag_id}`
`astro unpause {dag_id}`

**Relevant Links:**
https://github.com/astronomerio/incubator-airflow/blob/master/airflow/bin/cli.py#L306
https://github.com/teamclairvoyant/airflow-rest-api-plugin/blob/master/plugins/rest_api_plugin.py#L20

source: https://github.com/astronomerio/astronomer-cloud/issues/164

**Comment by andscoop** [comment]
Issue moved to [astronomerio/houston-api #7](https://github.com/astronomerio/houston-api/issues/7) via [**ZenHub**](https://www.zenhub.com/)
