### ISSUE TITLE
Astro init looks at parent directory

### ISSUE THREAD

**Issue by bonominijl** [astronomerio/astro-cli#103]
**Observation:** astro airflow deploy is traversing parent level directories for the first .astro file it finds. This results in child astro projects not working as expected.

**Steps to reproduce:**
Step 1: astro airflow init a parent level directory
Step 2: Create a new directory within the parent directory
Step 3: astro airflow init within the new child directory
Step 4: Run astro airflow deploy in your child directory

**Expected outcome:**
astro airflow init does not traverse parent directories, astro airflow deploy does not traverse parent directories

**Actual outcome:**
astro airflow init and astro airflow deploy traverse parent directories and push their contents rather than the current project directory.

**Story time:**
At some point I may have done an astro airflow init in my Documents folder. Later I created new project directories within the documents folder. When running an astro airflow init in the new project directory I was told that the existing project was being reinitialized. 

Running an astro airflow deploy pushed the entire contents of my Documents directory, rather than the current project folder I was in.

**Comment by schnie** [comment]
@andscoop I could see other people doing this pretty easily. Can we re-work the way the directory traversal works? Maybe traverse from `pwd` in the reverse direction?
