### ISSUE TITLE
Upgrade command reports new version if equal to current

### ISSUE THREAD

**Issue by schnie** [astronomerio/astro-cli#107]
Running `astro upgrade` when you are currently up to date reports that there is an upgrade available. It should just say that you are already up to date.
```
$ astro upgrade
Astro CLI Version: v0.2.1 (2018.07.19)
Astro CLI Latest: v0.2.1  (2018.07.19)
There is a more recent version of the Astronomer CLI available.
You can install the latest tagged release with the following command
        $ curl -sL https://install.astronomer.io | sudo bash
```

**Comment by andscoop** [comment]
Fixed in https://github.com/astronomerio/astro-cli/commit/cfe618afadeada08a20e630f8d85f6f2864742cf but not currently released. I will look into changes made and get a release out there

**Comment by andscoop** [comment]
Merged
