### ISSUE TITLE
404 not  when running cli install script

### ISSUE THREAD

**Issue by bonominijl** [astronomerio/astro-cli#109]
When running: `curl -sL https://install.astronomer.io | sudo bash` on linux, the install fails with the following error:

`cerebro@cerebral: ~
$ curl -sL https://install.astronomer.io | sudo bash
astronomerio/astro-cli: checking GitHub for latest tag
astronomerio/astro-cli: found version: https://api.github.com/repos/astronomerio/astro-cli/releases/12009259 for https://api.github.com/repos/astronomerio/astro-cli/releases/12009259/linux/amd64
astronomerio/astro-cli: downloading https://github.com/astronomerio/astro-cli/releases/download/https://api.github.com/repos/astronomerio/astro-cli/releases/12009259/astro_https://api.github.com/repos/astronomerio/astro-cli/releases/12009259_linux_amd64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found`:

Running on Ubuntu 18.04, tried in default xfce terminal and terminator emulator.

**Comment by andscoop** [comment]
It appears that downloader.sh is not able to find latest tag, can you humor me and try with the command below?

`curl https://raw.githubusercontent.com/astronomerio/astro-cli/master/godownloader.sh | bash -s -- -b /usr/local/bin`

**Comment by andscoop** [comment]
This appears to be the result of `curl` not always outputting newlines on return. I have opened an issue with curl
https://github.com/curl/curl/issues/2881

**Comment by andscoop** [comment]
This has been resolved, please see the curl issue linked in the last comment.
