### ISSUE TITLE
User installed binary should be astro not astro-cli

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astro-cli#12]
When installing as a user with `go get github.com/astronomerio/astro-cli`, the current binary is named `astro-cli`.

```
$ ls $GOBIN
astro-cli
```

Instead it should be just `astro` consistent with installing as a dev with `make build`.  However, it looks like it might not be possible to have the binary named differently than the package when installing via `go get`.

https://stackoverflow.com/questions/42706246/how-to-build-executable-with-name-other-than-golang-package

http://lucasfcosta.com/2017/02/07/Understanding-Go-Dependency-Management.html

@schnie / @cwurtz Do you know if it's possible?  If not, should we just have users set `alias astro=astro-cli` in their .bash_profile for now (assuming they aren't using the old CLI)?

**Comment by schnie** [comment]
I think we could eventually rename the project and everything back to just `astro`, once we're mostly done using the existing CLI. Maybe just make a note for now.

**Comment by tedmiston** [comment]
Cool - resolved with a note to call this closed for now via https://github.com/astronomerio/astro-cli/pull/14.
