### ISSUE TITLE
Handle CLI binary failing to download in install / update script

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astro-cli#120]
In my deploy the nginx load balancer crashed and failed to spin up.  So the CLI install command that was output includes a URL that won't work because the CNAME record doesn't exist yet (because the load balancer that it would point to hasn't / can't spin up yet).

Maybe we could add error handling in this script for when the curl call errors so it's more obvious?  @andscoop 

```
t-mbp:docker-airflow-clickstream-3 taylor$ astro version
Astro CLI Version: 0.2.3
Git Commit: 2b0941757aa272c54db5ae200221cb1b38d4e1b5

t-mbp:docker-airflow-clickstream-3 taylor$ curl -sL https://install.astronomer.example.com | sudo bash
Password:
t-mbp:docker-airflow-clickstream-3 taylor$ astro version
Astro CLI Version: 0.2.3
Git Commit: 2b0941757aa272c54db5ae200221cb1b38d4e1b5

t-mbp:docker-airflow-clickstream-3 taylor$ which astro
/usr/local/bin/astro
```

(Actual TLD replaced with example.com.)

**Comment by andscoop** [comment]
This is a problem with our curl command. I modified the curl install command in order to output to stdErr when URL does not work. I also created a PR which does the same for our helm charts.
