### ISSUE TITLE
Init clears packages and requirements

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astro-cli#130]
`astro airflow init` now resets the contents of requirements.txt and packages.txt. 

Since the .astro files get gitignored most of the time, this can be troublesome to a user who needs to re-init after a `git pull`

Steps to replicate:
1) Open a new directory
2) `astro airflow init`
3) modify either requirements.txt or packages.txt
4) run `astro airflow init`
5) requirements.txt and packages.txt will be empty.

**Comment by andscoop** [comment]
@vparekh94 Nice catch - this is now fixed in master
