### ISSUE TITLE
command to show which workspace you are auth'd

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astro-cli#132]
As a user, it would be convenient to be reminded which workspace I am about to deploy to, or show the workspace I am currently in.

astro airflow deploy should show the workspace name when it lists airflow deployment.

there should also be an "astro workspace show" type command that just shows which workspace is authenticated to.

**Comment by andscoop** [comment]
I'm going to add this info to the `astro airflow deploy` command. In the meantime you can see which workspace you are authenticated to using
`astro workspace list`. The information is also displayed when you switch cluster context with `astro cluster switch`

**Comment by andscoop** [comment]
This has been added to master branch as well as the release-0.6 branch. It will be released in 0.6.1
