### ISSUE TITLE
Editable Packages in requirements.txt breaking `astro airflow start`

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astro-cli#19]
Replication:
1.) add an editable package to your requirements.txt file such as 
`-e git+https://github.com/astronomerio/simple-salesforce@master#egg=simple-salesforce`
2.) run `astro airflow start`

**Comment by tedmiston** [comment]
@andscoop I have a hunch about this one.  Is this the line where it's breaking?

https://github.com/astronomerio/astronomer/blob/15f037884a353f117a05f229fc82ab526fa7e077/docker/platform/airflow/onbuild/Dockerfile#L25

**Comment by andscoop** [comment]
I believe this issue was the result of a missing git dependency in the packages.txt. After supplying git to `packages.txt` I am able to resolve this error.
