### ISSUE TITLE
curl to install

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#3]
`curl -o- https://astro-cli.astronomer.io/install.sh | bash`

**Comment by schnie** [comment]
Sounds like @andscoop made some good progress with `godownloader`, but that doesn't really "install" it to a location on the system PATH. We still need to wrap `godownloader` with a script or something it seems like. Any thoughts @andscoop @cwurtz @ryw ?

**Comment by schnie** [comment]
I'm going to attempt a quick script that we can host at `install.astronomer.io` (GCS bucket) that just wraps the `godownloader` script and passes it `-b /usr/local/bin` to download it to that dir. Will report back soon.

**Comment by schnie** [comment]
`curl -sL https://install.astronomer.io | sudo bash`
 
This should curl a small script that curls our `godownloader` script and passes it `/usr/local/bin`. It makes sure that it's run as root and issues a warning if not.

Anyone else wanna give it a shot to make sure it works?

**Comment by benjamingregory** [comment]
```
MacBook-Pro:~ tardis5$ curl -sL https://install.astronomer.io | sudo bash
Password:
astronomerio/astro-cli: checking GitHub for latest tag
astronomerio/astro-cli: found version: 0.0.2 for v0.0.2/darwin/amd64
astronomerio/astro-cli: downloading https://github.com/astronomerio/astro-cli/releases/download/v0.0.2/astro_0.0.2_darwin_amd64.tar.gz
astronomerio/astro-cli: downloading https://github.com/astronomerio/astro-cli/releases/download/v0.0.2/astro_0.0.2_checksums.txt
astronomerio/astro-cli: verifying checksums
astronomerio/astro-cli: installed as /usr/local/bin/astro

```
