### ISSUE TITLE
Command to Pull All Valid Release Names For A Project

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astro-cli#38]
A user needs to be aware of what projects they have running in the cloud for supplying arguments to deploy.

**Suggested Behavior**
- When a user runs `astro airflow deploy` with no supplied release name, CLI will prompt user with a list of valid release names they have access to.

- A new command that returns a list of projects (deploys) a user has access to.
  - `astro airflow ls` is a possibility

**SPIKE**
How much of this should live in houston? Have we drawn lines around what features the CLI wraps vs what houston will wrap?

**Comment by schnie** [comment]
When projects get created from the CLI `astro airflow create`, it should make a call to Houston. Houston will need to create a record in the `deployments` table in postgres, tying it to the users who have access to push to it.

`astro airflow ls` should just query Houston for the list of deployments the user is able to push to.

NGINX auth needs to be wired up (@cwurtz is on this) so docker pushes (eg `astro airflow deploy`) are first validated by checking to make sure the user has access to push to that particular deployment.

**Comment by cwurtz** [comment]
As of now we have an `astro airflow list` command to just list deployments, and `astro airflow deploy` on https://github.com/astronomerio/astro-cli/tree/feature/houston-api-integration will now prompt for a numeric selection for which deployment the user wants to deploy to.
