### ISSUE TITLE
Rename config.json to astro.json to avoid old CLI conflicts

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astro-cli#42]
Proposal to rename `./astro/config.json` to `./astro/astro.json` in order to avoid conflicts between configurations in the old CLI and the new CLI. This could make dev and internal work easier while we continue to support two CLIs.

**Comment by schnie** [comment]
Documenting that we talked offline and decided to change viper to use `yaml` instead of `json`. YAML is easier to work with and makes this problem go away.
