### ISSUE TITLE
Add Command to Update or Upgrade CLI to Latest

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astro-cli#50]
Add a command that allows user to update or upgrade the CLI from within the cli itself

`astro update`
or
`astro upgrade`

**Comment by andscoop** [comment]
Instead of a separate command, we should check for the latest version against the github api and compare that to the version that is installed. If cli is out of date we should prompt user with the install script cmd to upgrade.

[Github api call for astro-cli latest](https://api.github.com/repos/astronomerio/astro-cli/releases/latest)

**Comment by tedmiston** [comment]
What do you think about optionally distributing it as a Homebrew package?  Then people could just do a standard upgrade that way.

**Comment by andscoop** [comment]
Yeah I think we should do that - goreleaser gives us that ability when we're ready. We'll just need to detect if it was installed via homebrew and offer an alternative upgrade cmd output.

**Comment by schnie** [comment]
`astro upgrade` sounds good to me

**Comment by andscoop** [comment]
MVP for this will be 

`astro upgrade` which checks current version against the github latest version and spits out the install command (`curl -sL https://install.astronomer.io | sudo bash
`) if github latest is greater giving the user the option to upgrade.

**Comment by andscoop** [comment]
Completed in v0.3.0
