### ISSUE TITLE
google-cloud-logging package breaks builds

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astro-cli#57]
Including the package `google-cloud-logging` in the `requirements.txt` breaks builds.

This is because of a dependency in `google-cloud-logging` called `grpcio`. 

`grpcio` relies on `python-dev` system package to provide a file `Python.h`.

It appears that we also need to include some compiler tools that are not provided with alpine-linux by default.

Creating the following `packages.txt` file resolved the pip install issues we were having.

```
py-pip
python-dev
gcc
musl-dev
make
linux-headers
build-base
```

There is likely some redundancy in these packages as I did not have time to dig into everything that the [build-base](https://wiki.alpinelinux.org/wiki/GCC) package provided.

**Comment by andscoop** [comment]
Will close after it is verified it is working for customer needs as well.

**Comment by tedmiston** [comment]
@andscoop What is the py-pip system package (compared to just pip install pip)?

@schnie Any opposition to moving python-dev up to our base requirements?  I assumed it was already there.

**Comment by Knowa42** [comment]
The py-pip package needs to be removed from the packages.txt, otherwise it will break the install from requirements.txt file
