### ISSUE TITLE
Service accounts/access token

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astro-cli#67]
I just installed the DigitalOcean CLI `doctl` and the way they do auth is really clean.  You just create an auth token in the DO web app that's only shown once, then run `$ doctl auth init` and paste it in.

https://github.com/digitalocean/doctl/tree/f1efdf9409e8b3b1a6620db313a65d9b22847dec#authenticating-with-digitalocean

This would also improve the security of CLI deployments so a user could provide a separate key than their own password on a shared CLI server.

@andscoop @schnie @cwurtz What do you guys think?  Are we cool with doing the same setup?

Edit: I was bored, so I took a quick stab at seeing what I could do in 15 minutes here.  I'll probably lean on someone more experienced in Go and the CLI for help, but here's a start:

https://github.com/astronomerio/astro-cli/compare/access-token

**Comment by schnie** [comment]
Pretty much, but on a `astro auth login` we need to spit out a link that takes a user to the OAuth provider list (Google for now), where they log in with the provider and get redirected back to us where they get a token. They paste that token in on the CLI to complete the login.

Should be pretty close to how DC/OS works.

**Comment by cwurtz** [comment]
Service accounts are already planned, one use case if for use in CI to allow them to auth using a token instead of a user/pass.  Whether you

**Comment by schnie** [comment]
Closing in favor of tracking this feature on one issue - astronomerio/houston-api#41
