### ISSUE TITLE
Implement OAuth login

### ISSUE THREAD

**Issue by cwurtz** [astronomerio/astro-cli#72]
Implement OAuth login flow similar to what Greg outlined in https://github.com/astronomerio/astro-cli/issues/67

The flow should be:
User types auth command, a link should get output for the user to auth with.  They will copy/paste the link, and be directed to a webpage.  This will click a button which will open a popup to auth with google (or whatever other provides we eventually support).  Once auth'd the window will close and they will be redirected to a page with a link for them to copy/paste back into the CLI.

**Comment by andscoop** [comment]
implemented on master
