### ISSUE TITLE
Include airflow.cfg in init

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astro-cli#78]
As a user, I want to change settings in airflow.cfg for my airflow deployment. I might want to change default views for DAGs, have DAGs be unpaused by default, or change a few other non-infrastructure related settings.

We'd need to override certain settings so that  the user can't touch them for safety, but there are definitely some settings that we can give the user control over.

It might also be nice to rope this into the UI at some point.

**Comment by schnie** [comment]
Users should be able to supply an `airflow.cfg` in their project for baseline settings, then optionally override some environment variables through the UI/CLI on a per-deployment basis (differences between dev and prod). Some settings, like executor will be overridden by the astronomer system that a user cannot change.

airflow.cfg < deployment settings < astronomer system settings

We should support the `airflow.cfg` tweaks at a minimm, per-deployment settings can be defered to if/when a customer needs it.

**Comment by andscoop** [comment]
@schnie I think this is needed - but one thing to consider is that an `airflow.cfg` can be changed across airflow versions. This will mean that the CLI may need to maintain multiple .cfg files. We avoid some of these problems by requiring a user to override through ENVs.

**Comment by schnie** [comment]
@andscoop well maybe we shouldn't actually do anything for this except document the fact that adding an `airflow.cfg` file to your project will be included and used. I don't really want to have to maintain the different `airflow.cfg` templates in our stuff. Technically this should already work.

**Comment by andscoop** [comment]
I will add this information to this guide
http://enterprise.astronomer.io/guides/configuring-airflow/index.html

**Comment by andscoop** [comment]
It is done 
https://github.com/astronomerio/astronomer-ee/commit/855d0549e6896c06f97ea96e541dde8d824f251f
