### ISSUE TITLE
Auto create ~/.bash_profile

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astro-cli#79]
@vparekh94 and I just had a support call with customer troubleshooting getting started with the CLI. 
 The CLI failed to install because it couldn't add the PATH command to the bash profile.  The command failed because the user did not have a `~/.bash_profile` created yet.

@andscoop @cwurtz @schnie What do we think about auto creating an empty `~/.bash_profile` when it doesn't exist?

**Comment by andscoop** [comment]
@tedmiston What OS? If a user has deleted their `~/.bash_profile` they have likely done so for a reason. I'm not opposed, just one thing to consider

**Comment by tedmiston** [comment]
He was on macOS (not sure which version).  In his case the file was renamed, potentially out of error or mistake because he had no other commands in it.

Do you know if an empty `~/.bash_profile` is automatically created for a new user account on macOS / Linux?  I'm not sure.

If it's automatically created and the user doesn't have one, perhaps we could output an error message something like:

```
Please create a .bash_profile so that we can add the CLI binary to your $PATH.

    $ touch ~/.bash_profile
```

What do you think?

**Comment by cwurtz** [comment]
I'm 90% sure either .bash_profile or .bashrc has to be created on OS X, but could be misremembering.

In my opinion, if the file doesn't exist we should just output a message like:

```
Couldn't automatically add astro-cli to your path.  Add the following to your profile:
export PATH="$PATH:/path/to/astro"
```

That being said, isn't astro-cli added to /usr/local/bin or something?

**Comment by tedmiston** [comment]
Yeah, personally I prefer being given the command to add to my profile vs having a script modify my profile for me.  Partly because I put most commands in .bashrc instead of .bash_profile myself.

**Comment by schnie** [comment]
Yea, `astro` should be installed into standard path that should already exist in `$PATH`. Where in our installation does it append this?

**Comment by ryw** [comment]
i'd say we should detect presence of ~/.bash_profile and tell them they need create it before proceeding, could link to a guide
