### ISSUE TITLE
Output Scheduler Logs for Local Development

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astro-cli#88]
As a user, having scheduler logs when debugging a custom plugin or workflow would be really helpful. Often times, the error message exposed in the UI doesn't contain the full traceback.

Something like `astro airflow start --logs` or something would be a great.

I know a few customers have bought this up for cloud CLI, so just wanted to make sure that feedback was captured here.

**Comment by andscoop** [comment]
@vparekh94 You can access the logs via `docker logs [CONTAINER_ID]`. We can look into wrapping it, but not a priority since this feature is already supported. Leave this issue open for anyone else who wants to access webserver, scheduler or postgres logs.

**Comment by benjamingregory** [comment]
@vparekh94 @andscoop @petedejoy 

Do we have a guide for Andy's suggested stop gap yet? As Viraj suggested, users are going to want to see logs so we should definitely have a public recommendation.
