### ISSUE TITLE
Executing Remote Kubernetes Commands with CLI

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#90]
Have we made it easy to use the Airflow CLI remotely (i.e. run commands from your local terminal that execute in the cloud Airflow)? If not, should this be on roadmap?

**Comment by schnie** [comment]
It should def be on the roadmap. Do not have this yet.

**Comment by andscoop** [comment]
Moving for visibility

**Comment by andscoop** [comment]
Issue moved to [astronomerio/astronomer-ee #132](https://github.com/astronomerio/astronomer-ee/issues/132) via [**ZenHub**](https://www.zenhub.com/)
