### ISSUE TITLE
Add ability to duplicate pools, variables and connections between two Airflow instances

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#91]
@andscoop commented on [Fri Feb 09 2018](https://github.com/astronomerio/astronomer-ee/issues/18)

As a user of the Astronomer Enterprise, I would like to be able to migrate pools, connection information and Airflow Variables between various Airflow instances, in order to save significant amounts of time when deploying airflow instances for many teams or users in a single organization or team.

possible cli cmd
`astro airflow copy [src-instance-release-name] [dst-instance-release-name] [args]`

possible arguments

-a | copy all possibilities between instances
-v | copy airflow variables between instances
-c | copy airflow connections between instances
-p | copy airflow pools between instances

Each argument could also take an optional fp to point to a json file whitelisting all pools, connections and variables by key that need to be copied. This would prevent sensitive connections on one instance from being copied while allowing user to copy everything else.

---

@benjamingregory commented on [Fri Feb 09 2018](https://github.com/astronomerio/astronomer-ee/issues/18#issuecomment-364543311)

Copying connection info would be 💯

**Comment by andscoop** [comment]
This would be a great feature, but it is more platform level than strictly CLI level. Moving for visibility.

**Comment by andscoop** [comment]
Issue moved to [astronomerio/astronomer-ee #131](https://github.com/astronomerio/astronomer-ee/issues/131) via [**ZenHub**](https://www.zenhub.com/)
