### ISSUE TITLE
Specify install location

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#93]
@vparekh94 commented on [Wed Apr 04 2018](https://github.com/astronomerio/astronomer-ee/issues/60)

We've had a few customers attempt to deploy the CLI on remote boxes (cloud compute boxes, EC2s, etc.)

There's something in the install that breaks these. 

We should make it clear that the CLI is meant for a local machine.

---

@vparekh94 commented on [Wed Apr 11 2018](https://github.com/astronomerio/astronomer-ee/issues/60#issuecomment-380526713)

Update - they were able to install it using the go binary instead of the curl command - no idea why. Not assigning to anyone because it doesn't seem urgent, but eventually we should look into this.

**Comment by andscoop** [comment]
@vparekh94 If we can duplicate this one I can take a look

**Comment by andscoop** [comment]
Likely related to the more specific ticket https://github.com/astronomerio/astro-cli/issues/79
