### ISSUE TITLE
Support installing a pip package line with spaces

### ISSUE THREAD

**Issue by ryw** [astronomerio/astro-cli#94]
@tedmiston commented on [Wed May 02 2018](https://github.com/astronomerio/astronomer-ee/issues/78)

Reported by Noah from 84.51.

Having this line in `packages.txt` causes the install to break and the package does not get installed.

```
-e git+https://github.com/dominodatalab/python-domino.git#egg=domino
```

I had him workaround it by changing that particular dependency to

```
git+https://github.com/dominodatalab/python-domino.git
```

which worked.

(It's a common misconception that the `-e` is needed for installing any package from git, but it's not actually required unless you actually intend to edit the code of the package.)

This suggests to me that our `pip install` command is not quoting the lines from requirements.txt.  It's possible we don't yet support lines that contain spaces.

Still the `-e` is a valid format for pip and we should support it.

@cwurtz @schnie @andscoop Has anyone tried this personally?  Who's the best person to add support for this style of install?

---

@andscoop commented on [Wed May 02 2018](https://github.com/astronomerio/astronomer-ee/issues/78#issuecomment-386060033)

duplicate of https://github.com/astronomerio/astro-cli/issues/19 . I am going to leave both open until we can resolve since these issues are in separate repo's for more visibility.

---

@tedmiston commented on [Wed May 02 2018](https://github.com/astronomerio/astronomer-ee/issues/78#issuecomment-386064728)

Sounds good - we can scope this one to be the backend change that needs to be made.  And scope the one you linked to any required changes for the CLI.

**Comment by andscoop** [comment]
This was caused by dep issues in `packages.txt`
https://github.com/astronomerio/astro-cli/issues/19
