### ISSUE TITLE
Ability to set "deploy" branch in CLI 

### ISSUE THREAD

**Issue by benjamingregory** [astronomerio/astro-cli#95]
As a user of the Astro CLI who is working on multiple branches of a project, I want the ability to safeguard against an errant deploy by setting a `Deploy` branch (defaults to Master). If the user then tries to deploy from a separate branch, the CLI would throw a warning and ask to either switch branches or force deploy.

**Comment by andscoop** [comment]
Can definitely take a stab at this once #96 changes are in place
